---
- module-name: 'nidra_gui.launcher'
  implicit-imports:
    depends:
      - 'mne'
      - 'scipy'
      - 'pandas'
      - 'mne.io'
      - 'mne.datasets'
      - 'scipy.linalg'
      - 'scipy.spatial'
      - 'pandas._libs'
      - 'pandas.io'
  data-dirs:
    - source: '{MAIN_DIRECTORY}/NIDRA/nidra_gui/neutralino'
      target: 'neutralino'
    - source: '{MAIN_DIRECTORY}/NIDRA/docs'
      target: 'docs'
    - source: '{MAIN_DIRECTORY}/NIDRA/models'
      target: 'models'
    - source: '{MAIN_DIRECTORY}/NIDRA/examples'
      target: 'examples'
  dlls:
    - '{MAIN_DIRECTORY}/NIDRA/dll/*.dll'